name: Python Lint

on:
  push:
    branches:
      - main  # Run on push to main
  pull_request:
    branches:
      - main  # Run on pull requests to main

jobs:
  lint-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup pip configuration
      run: |
        cat >$HOME/.config/pip/pip.conf <<EOF
        [global]
        index-url = https://artifactory.eng.vmware.com/artifactory/api/pypi/sebu-edgeops-pypi-local/simple
        extra-index-url = https://artifactory.eng.vmware.com/artifactory/api/pypi/pypi-virtual/simple
        EOF

    - name: Install Python dependencies
      run: |
        pip install -r ci/jjb/scripts/requirements.txt

    - name: Run pylint
      env:
        DIR: ci/jjb/scripts  # You can change this as needed
      run: |
        echo 'Running pylint'
        pylint --fail-under=9.5 $DIR/*.py
